### ISSUE TITLE
Exception Involving Morphology class

### ISSUE THREAD

**Issue by PhaniJella** [oudalab/biryani#15]
**Program Details** 
Annotators
1) tokenize
2) ssplit
3)pos
4)parse

**Program Parameters**
1) Number of Threads: 128
2) Batch size or number of documents : 1000

**Exception**
java.lang.Error: Error: pushback value was too large
    at edu.stanford.nlp.process.Morpha.zzScanError(Morpha.java)
    at edu.stanford.nlp.process.Morpha.yypushback(Morpha.java)
    at edu.stanford.nlp.process.Morpha.next(Morpha.java)
    at edu.stanford.nlp.process.Morphology.lemmatize(Morphology.java:156)
    at edu.stanford.nlp.process.Morphology.lemma(Morphology.java:110)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.correctWHAttachment(UniversalEnglishGrammaticalStructure.java:689)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.postProcessDependencies(UniversalEnglishGrammaticalStructure.java:173)
    at edu.stanford.nlp.trees.GrammaticalStructure.getDeps(GrammaticalStructure.java:560)
    at edu.stanford.nlp.trees.GrammaticalStructure.<init>(GrammaticalStructure.java:215)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.<init>(UniversalEnglishGrammaticalStructure.java:92)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.<init>(UniversalEnglishGrammaticalStructure.java:71)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructureFactory.newGrammaticalStructure(UniversalEnglishGrammaticalStructureFactory.java:29)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructureFactory.newGrammaticalStructure(UniversalEnglishGrammaticalStructureFactory.java:5)
    at edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ParserAnnotatorUtils.java:59)
    at edu.stanford.nlp.pipeline.ParserAnnotator.finishSentence(ParserAnnotator.java:290)
    at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:260)
    at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:98)
    at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:71)
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:499)
    at edu.stanford.nlp.pipeline.AnnotationPipeline$1.lambda$next$36(AnnotationPipeline.java:148)
    at edu.stanford.nlp.util.logging.Redwood$Util$1$1.run(Redwood.java:1071)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Exception 2**

java.lang.StringIndexOutOfBoundsException: String index out of range: -4
    at java.lang.String.<init>(String.java:196)
    at edu.stanford.nlp.process.Morpha.yytext(Morpha.java)
    at edu.stanford.nlp.process.Morpha.next(Morpha.java)
    at edu.stanford.nlp.process.Morphology.lemmatize(Morphology.java:157)
    at edu.stanford.nlp.process.Morphology.lemma(Morphology.java:110)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.correctWHAttachment(UniversalEnglishGrammaticalStructure.java:689)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.postProcessDependencies(UniversalEnglishGrammaticalStructure.java:173)
    at edu.stanford.nlp.trees.GrammaticalStructure.getDeps(GrammaticalStructure.java:560)
    at edu.stanford.nlp.trees.GrammaticalStructure.<init>(GrammaticalStructure.java:215)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.<init>(UniversalEnglishGrammaticalStructure.java:92)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.<init>(UniversalEnglishGrammaticalStructure.java:71)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructureFactory.newGrammaticalStructure(UniversalEnglishGrammaticalStructureFactory.java:29)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructureFactory.newGrammaticalStructure(UniversalEnglishGrammaticalStructureFactory.java:5)
    at edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ParserAnnotatorUtils.java:61)
    at edu.stanford.nlp.pipeline.ParserAnnotator.finishSentence(ParserAnnotator.java:290)
    at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:260)
    at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:98)
    at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:71)
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:499)
    at edu.stanford.nlp.pipeline.AnnotationPipeline$1.lambda$next$36(AnnotationPipeline.java:148)
    at edu.stanford.nlp.util.logging.Redwood$Util$1$1.run(Redwood.java:1071)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
java.lang.ArrayIndexOutOfBoundsException
    at edu.stanford.nlp.process.Morpha.zzRefill(Morpha.java)
    at edu.stanford.nlp.process.Morpha.next(Morpha.java)
    at edu.stanford.nlp.process.Morphology.lemmatize(Morphology.java:156)
    at edu.stanford.nlp.process.Morphology.lemma(Morphology.java:110)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.correctWHAttachment(UniversalEnglishGrammaticalStructure.java:689)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.postProcessDependencies(UniversalEnglishGrammaticalStructure.java:173)
    at edu.stanford.nlp.trees.GrammaticalStructure.getDeps(GrammaticalStructure.java:560)
    at edu.stanford.nlp.trees.GrammaticalStructure.<init>(GrammaticalStructure.java:215)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.<init>(UniversalEnglishGrammaticalStructure.java:92)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructure.<init>(UniversalEnglishGrammaticalStructure.java:71)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructureFactory.newGrammaticalStructure(UniversalEnglishGrammaticalStructureFactory.java:29)
    at edu.stanford.nlp.trees.UniversalEnglishGrammaticalStructureFactory.newGrammaticalStructure(UniversalEnglishGrammaticalStructureFactory.java:5)
    at edu.stanford.nlp.pipeline.ParserAnnotatorUtils.fillInParseAnnotations(ParserAnnotatorUtils.java:59)
    at edu.stanford.nlp.pipeline.ParserAnnotator.finishSentence(ParserAnnotator.java:290)
    at edu.stanford.nlp.pipeline.ParserAnnotator.doOneSentence(ParserAnnotator.java:260)
    at edu.stanford.nlp.pipeline.SentenceAnnotator.annotate(SentenceAnnotator.java:98)
    at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:71)
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:499)
    at edu.stanford.nlp.pipeline.AnnotationPipeline$1.lambda$next$36(AnnotationPipeline.java:148)
    at edu.stanford.nlp.util.logging.Redwood$Util$1$1.run(Redwood.java:1071)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by cegme** [comment]
This is in the same class as a the other exception. We may need to create our create our own annotation pipeline. We are not the first ones with this problem http://stackoverflow.com/questions/30676291/concurrent-processing-using-stanford-corenlp-3-5-2. 

Identify the classes that are being called by out pipeline. You can use eclipse to walk through the pipeline process. We will need add synchronization guards around the classes that we find to be not thread safe.

**Comment by cegme** [comment]
We discussed as one solution, to restart the failed docker when an exception occurs. Using the command line `docker run --restart=on-failure` will restart the failed containers.

This restarted docker will re-parse some unACKed messages. We should be able to add a flag to check to see if a restart just happened and in this case only insert items that are not present in SQLite.
