### ISSUE TITLE
Parse Issue

### ISSUE THREAD

**Issue by PhaniJella** [oudalab/biryani#9]
**ISSUE 1:**

java.lang.IllegalArgumentException
    at edu.stanford.nlp.semgraph.SemanticGraph.parentPairs(SemanticGraph.java:699)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$DEPENDENT$1.advance(GraphRelation.java:324)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$SearchNodeIterator.initialize(GraphRelation.java:1102)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$SearchNodeIterator.<init>(GraphRelation.java:1083)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$DEPENDENT$1.<init>(GraphRelation.java:309)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$DEPENDENT.searchNodeIterator(GraphRelation.java:309)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.resetChildIter(NodePattern.java:320)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.<init>(NodePattern.java:315)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern.matcher(NodePattern.java:276)
    at edu.stanford.nlp.semgraph.semgrex.CoordinationPattern$CoordinationMatcher.<init>(CoordinationPattern.java:147)
    at edu.stanford.nlp.semgraph.semgrex.CoordinationPattern.matcher(CoordinationPattern.java:121)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.resetChild(NodePattern.java:339)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.goToNextNodeMatch(NodePattern.java:438)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.matches(NodePattern.java:555)
    at edu.stanford.nlp.semgraph.semgrex.SemgrexMatcher.find(SemgrexMatcher.java:182)
    at edu.stanford.nlp.dcoref.Mention.findDependentVerb(Mention.java:1068)
    at edu.stanford.nlp.dcoref.Mention.setDiscourse(Mention.java:319)
    at edu.stanford.nlp.dcoref.Mention.process(Mention.java:237)
    at edu.stanford.nlp.dcoref.Mention.process(Mention.java:244)
    at edu.stanford.nlp.dcoref.MentionExtractor.arrange(MentionExtractor.java:215)
    at edu.stanford.nlp.dcoref.MentionExtractor.arrange(MentionExtractor.java:133)
    at edu.stanford.nlp.dcoref.MentionExtractor.arrange(MentionExtractor.java:108)
    at edu.stanford.nlp.pipeline.DeterministicCorefAnnotator.annotate(DeterministicCorefAnnotator.java:120)
    at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:71)
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:499)
    at edu.stanford.nlp.pipeline.AnnotationPipeline$1.lambda$next$36(AnnotationPipeline.java:148)
    at edu.stanford.nlp.util.logging.Redwood$Util$1$1.run(Redwood.java:1071)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**ISSUE 2:**

java.lang.IllegalArgumentException
    at edu.stanford.nlp.semgraph.SemanticGraph.parentPairs(SemanticGraph.java:699)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$DEPENDENT$1.advance(GraphRelation.java:324)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$SearchNodeIterator.initialize(GraphRelation.java:1102)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$SearchNodeIterator.<init>(GraphRelation.java:1083)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$DEPENDENT$1.<init>(GraphRelation.java:309)
    at edu.stanford.nlp.semgraph.semgrex.GraphRelation$DEPENDENT.searchNodeIterator(GraphRelation.java:309)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.resetChildIter(NodePattern.java:320)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.<init>(NodePattern.java:315)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern.matcher(NodePattern.java:276)
    at edu.stanford.nlp.semgraph.semgrex.CoordinationPattern$CoordinationMatcher.<init>(CoordinationPattern.java:147)
    at edu.stanford.nlp.semgraph.semgrex.CoordinationPattern.matcher(CoordinationPattern.java:121)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.resetChild(NodePattern.java:339)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.goToNextNodeMatch(NodePattern.java:438)
    at edu.stanford.nlp.semgraph.semgrex.NodePattern$NodeMatcher.matches(NodePattern.java:555)
    at edu.stanford.nlp.semgraph.semgrex.SemgrexMatcher.find(SemgrexMatcher.java:182)
    at edu.stanford.nlp.dcoref.Mention.findDependentVerb(Mention.java:1068)
    at edu.stanford.nlp.dcoref.Mention.setDiscourse(Mention.java:319)
    at edu.stanford.nlp.dcoref.Mention.process(Mention.java:237)
    at edu.stanford.nlp.dcoref.Mention.process(Mention.java:244)
    at edu.stanford.nlp.dcoref.MentionExtractor.arrange(MentionExtractor.java:215)
    at edu.stanford.nlp.dcoref.MentionExtractor.arrange(MentionExtractor.java:133)
    at edu.stanford.nlp.dcoref.MentionExtractor.arrange(MentionExtractor.java:108)
    at edu.stanford.nlp.pipeline.DeterministicCorefAnnotator.annotate(DeterministicCorefAnnotator.java:120)
    at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:71)
    at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:499)
    at edu.stanford.nlp.pipeline.AnnotationPipeline$1.lambda$next$36(AnnotationPipeline.java:148)
    at edu.stanford.nlp.util.logging.Redwood$Util$1$1.run(Redwood.java:1071)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by cegme** [comment]
We will need to add code to check the length of the sentences before a parse. If a sentence is above a maximum size we can split the sentence. 
Please find the a sample of the sentences that cause these errors and paste them here.
